#!/bin/sh -ex

ORG_PATH="github.com/coreos"
REPO_PATH="${ORG_PATH}/discovery.etcd.io"

export GOPATH=${PWD}/gopath

rm -f $GOPATH/src/${REPO_PATH}
mkdir -p $GOPATH/src/${ORG_PATH}
ln -s ${PWD} $GOPATH/src/${REPO_PATH}

eval $(go env)

go get github.com/tools/godep
godep restore

# Static compilation is useful when etcd is run in a container
CGO_ENABLED=0 go build -a -installsuffix cgo -ldflags "-s" -o bin/discovery-$GOOS-$GOARCH-static ${REPO_PATH}
