#!/bin/sh -e -x
# build discovery statically for the docker container, then build the container

cat >.payload <<EOF
go run third_party.go clean -i net
go run third_party.go install -tags netgo std
CGO_ENABLED=0 go run third_party.go build -a -tags netgo --ldflags '-w -extldflags=-static' -o bin/discovery-linux64-static github.com/coreos/discovery.etcd.io
EOF

echo "building statically-linked discovery.etcd.io..."
tar cvzf - handlers http pkg third_party discovery.go third_party.go .payload | ssh -i ~/.vagrant.d/insecure_private_key core@192.168.56.100 "cat - | tar xzvf - -C /home/core/"
#docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp golang:latest bash .payload
docker run --rm -v /home/core:/usr/src/myapp -w /usr/src/myapp golang:latest bash .payload
rm -f .payload
scp -r -i ~/.vagrant.d/insecure_private_key core@192.168.56.100:/home/core/bin/ .

echo "building docker container..."
docker build .
